### PR TITLE
Add documentation about on-behalf tokens

### PR DESCRIPTION
**Pull request by srozen**

### CODE REVIEW

**Review by tosch — APPROVED** [review]
💯

**Comment by jalyna** [comment]
@srozen well done! It seems this is not deployed yet as currently docs needs a manual deployment. Can you please have a look so the latest changes are live?

**Comment by srozen** [comment]
> @srozen well done! It seems this is not deployed yet as currently docs needs a manual deployment. Can you please have a look so the latest changes are live?

Hello @jalyna , looks like it is supposed to be automatic on main update but my merge didn't trigger the deploy for some reason 😲 https://dashboard.heroku.com/pipelines/5a8803ef-4ad4-4758-834c-f135d1622568

**Comment by jalyna** [comment]
@srozen no we don't use the github integration anymore on heroku for security reasons. Please do it manually for now via heroku cli :)

We should maybe reserve some time to use GH actions here as well.

**Pull request merged**
